pipeline:
  identifier: Build_aidanoc15_harness_java_demo_1788123732322
  name: Build harness-java-demo
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: GoInstallBuildTest
                  identifier: GoInstallBuildTest
                  spec:
                    shell: Bash
                    command: |-
                      mvn clean package
                      docker build -t aidanoconnell/harness-java-demo:1.0 .
                      docker push aidanoconnell/harness-java-demo:1.0
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1788122945839
        repoName: aidanoc15/harness-java-demo
        build: <+input>
